import "../CSS/home.css";
import "../CSS/parallax_background.css";
import React, { useState } from "react";
import { Background } from "./Background";

export function MainTable() {
  const ref = React.useRef(null);

  const [animation, setAnimation] = useState("static");

  const [show, setShow] = useState("hidden");
  const [link, setLink] = useState(null);
  const handleClose = () => setShow("hidden");
  const handleShow = () => setShow("showed");

  function toggleAnimation() {
    if (animation === "parallax") {
      setAnimation("static");
    } else {
      setAnimation("parallax");
    }
  }

  function clickHandler(link) {
    setLink(
      "https://upload.wikimedia.org/wikipedia/commons/4/40/Hiragana_%E3%81%B2_stroke_order_animation.gif"
    );
    handleShow();
  }

  React.useLayoutEffect(() => {
    Background(ref);
  }, []);

  return (
    <div ref={ref} className={animation === "parallax" ? "parallax" : "static"}>
      <table>
        <tbody>
          <tr>
            <td
              id="a"
              onMouseLeave={handleClose}
              onClick={() => {
                clickHandler();
              }}
            >
              <ul>
                <li>あ</li>
                <li>A</li>
              </ul>
            </td>
            <td
              id="i"
              onMouseLeave={handleClose}
              onClick={() => {
                clickHandler();
              }}
            >
              <ul>
                <li>い</li>
                <li>I</li>
              </ul>
            </td>
            <td>
              <ul>
                <li>う</li>
                <li>U</li>
              </ul>
            </td>
            <td>
              <ul>
                <li>え</li>
                <li>E</li>
              </ul>
            </td>
            <td>
              <ul>
                <li>お</li>
                <li>O</li>
              </ul>
            </td>
          </tr>

          <tr>
            <td>
              <ul>
                <li>か</li>
                <li>KA</li>
              </ul>
            </td>
            <td>
              <ul>
                <li>き</li>
                <li>KI</li>
              </ul>
            </td>
            <td>
              <ul>
                <li>く</li>
                <li>KU</li>
              </ul>
            </td>
            <td>
              <ul>
                <li>け</li>
                <li>KE</li>
              </ul>
            </td>
            <td>
              <ul>
                <li>こ</li>
                <li>KO</li>
              </ul>
            </td>
          </tr>

          <tr>
            <td>
              <ul>
                <li>さ</li>
                <li>SA</li>
              </ul>
            </td>
            <td>
              <ul>
                <li>し</li>
                <li>SHI</li>
              </ul>
            </td>
            <td>
              <ul>
                <li>す</li>
                <li>SU</li>
              </ul>
            </td>
            <td>
              <ul>
                <li>せ</li>
                <li>SE</li>
              </ul>
            </td>
            <td>
              <ul>
                <li>そ</li>
                <li>SO</li>
              </ul>
            </td>
          </tr>

          <tr>
            <td>
              <ul>
                <li>た</li>
                <li>TA</li>
              </ul>
            </td>
            <td>
              <ul>
                <li>ち</li>
                <li>CHI</li>
              </ul>
            </td>
            <td>
              <ul>
                <li>つ</li>
                <li>TSU</li>
              </ul>
            </td>
            <td>
              <ul>
                <li>て</li>
                <li>TE</li>
              </ul>
            </td>
            <td>
              <ul>
                <li>と</li>
                <li>TO</li>
              </ul>
            </td>
          </tr>

          <tr>
            <td>
              <ul>
                <li>な</li>
                <li>NA</li>
              </ul>
            </td>
            <td>
              <ul>
                <li>に</li>
                <li>NI</li>
              </ul>
            </td>
            <td>
              <ul>
                <li>ぬ</li>
                <li>NU</li>
              </ul>
            </td>
            <td>
              <ul>
                <li>ね</li>
                <li>NE</li>
              </ul>
            </td>
            <td>
              <ul>
                <li>の</li>
                <li>NO</li>
              </ul>
            </td>
          </tr>

          <tr>
            <td>
              <ul>
                <li>は</li>
                <li>HA</li>
              </ul>
            </td>
            <td>
              <ul>
                <li>ひ</li>
                <li>HI</li>
              </ul>
            </td>
            <td>
              <ul>
                <li>ふ</li>
                <li>FU</li>
              </ul>
            </td>
            <td>
              <ul>
                <li>へ</li>
                <li>HE</li>
              </ul>
            </td>
            <td>
              <ul>
                <li>ほ</li>
                <li>HO</li>
              </ul>
            </td>
          </tr>

          <tr>
            <td>
              <ul>
                <li>ま</li>
                <li>MA</li>
              </ul>
            </td>
            <td>
              <ul>
                <li>み</li>
                <li>MI</li>
              </ul>
            </td>
            <td>
              <ul>
                <li>む</li>
                <li>MU</li>
              </ul>
            </td>
            <td>
              <ul>
                <li>め</li>
                <li>ME</li>
              </ul>
            </td>
            <td>
              <ul>
                <li>も</li>
                <li>MO</li>
              </ul>
            </td>
          </tr>

          <tr>
            <td>
              <ul>
                <li>や</li>
                <li>YA</li>
              </ul>
            </td>
            <td>
              <ul>
                <li></li>
                <li></li>
              </ul>
            </td>
            <td>
              <ul>
                <li>ゆ</li>
                <li>YU</li>
              </ul>
            </td>
            <td>
              <ul>
                <li></li>
                <li></li>
              </ul>
            </td>
            <td>
              <ul>
                <li>よ</li>
                <li>YO</li>
              </ul>
            </td>
          </tr>

          <tr>
            <td>
              <ul>
                <li>ら</li>
                <li>RA</li>
              </ul>
            </td>
            <td>
              <ul>
                <li>り</li>
                <li>RI</li>
              </ul>
            </td>
            <td>
              <ul>
                <li>る</li>
                <li>RU</li>
              </ul>
            </td>
            <td>
              <ul>
                <li>れ</li>
                <li>RE</li>
              </ul>
            </td>
            <td>
              <ul>
                <li>ろ</li>
                <li>RO</li>
              </ul>
            </td>
          </tr>

          <tr>
            <td>
              <ul>
                <li>わ</li>
                <li>WA</li>
              </ul>
            </td>
            <td>
              <ul>
                <li></li>
                <li></li>
              </ul>
            </td>
            <td>
              <ul>
                <li></li>
                <li></li>
              </ul>
            </td>
            <td>
              <ul>
                <li></li>
                <li></li>
              </ul>
            </td>
            <td>
              <ul>
                <li>を</li>
                <li>WO</li>
              </ul>
            </td>
          </tr>

          <tr>
            <td>
              <ul>
                <li>ん</li>
                <li>N</li>
              </ul>
            </td>
            <td>
              <ul>
                <li></li>
                <li></li>
              </ul>
            </td>
            <td>
              <ul>
                <li></li>
                <li></li>
              </ul>
            </td>
            <td>
              <ul>
                <li></li>
                <li></li>
              </ul>
            </td>
            <td>
              <ul>
                <li></li>
                <li></li>
              </ul>
            </td>
          </tr>
        </tbody>
      </table>
      <div class={show} id="popout">
        <img alt="hi" src={link} />
      </div>
      <button class="animationBtn" onClick={toggleAnimation}>
        Animation
      </button>
    </div>
  );
}
